name = "Rock Soup"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f5743517ca15c456c4eb2dba0115caebe7689ed1ab9e8688e272b7dac2d9e64"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
